// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/1/2025, 9:23:56
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/xampp/htdocs/projecte3/prj-final-grupo3/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/plugins/**/*.{js,ts,mjs}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/composables/**/*.{js,ts,mjs}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/utils/**/*.{js,ts,mjs}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/projecte3/prj-final-grupo3/front/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;