// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/30/2025, 12:38:57 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/aivanantonio/Desktop/prj-final-grupo3/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/plugins/**/*.{js,ts,mjs}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/composables/**/*.{js,ts,mjs}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/utils/**/*.{js,ts,mjs}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/app.config.{js,ts,mjs}","/Users/aivanantonio/Desktop/prj-final-grupo3/front/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;